Areas/Admin/Controllers/AdminDashBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace InventoryApplication.Areas.Admin.Controllers
{
    public class AdminDashBoardController : Controller
    {
        [Area("Admin")]
        public IActionResult DashBoard()
        {
            return View();
        }
    }
}

Areas/Admin/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InventoryApplication.Areas.Admin.Models;
using InventoryApplication.Areas.Admin.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace InventoryApplication.Areas.Admin.Controllers
{
    public class BranchController : Controller
    {
        BranchAccessLayer objCustomer = new BranchAccessLayer();
        [Area("Admin")]

        public ActionResult GetAllEmpDetails()
        {

            BranchViewModel EmpRepo = new BranchViewModel();
            ModelState.Clear();
            return View(EmpRepo.GetAllEmployees());
        }
        // GET: Employee/AddEmployee 
        [Area("Admin")]
        public ActionResult AddEmployee()
        {
            return View();
        }

        // POST: Employee/AddEmployee
        [Area("Admin")]
        [HttpPost]
        public ActionResult AddEmployee(BranchModel Emp)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    BranchViewModel EmpRepo = new BranchViewModel();

                    if (EmpRepo.AddEmployee(Emp))
                    {
                        ViewBag.Message = "Branch details added successfully";
                    }
                }

                return View();
            }
            catch
            {
                return View();
            }
        }
        [Area("Admin")]
        // GET: Employee/EditEmpDetails/5    
        public ActionResult EditEmpDetails(int id)
        {
            BranchViewModel EmpRepo = new BranchViewModel();



            return View(EmpRepo.GetAllEmployees().Find(Emp => Emp.Id == id));

        }

        // POST: Employee/EditEmpDetails/5    
        [HttpPost]
        [Area("Admin")]
        public ActionResult EditEmpDetails(int id, BranchModel obj)
        {
            try
            {
                BranchViewModel EmpRepo = new BranchViewModel();

                EmpRepo.UpdateEmployee(obj);
                return RedirectToAction("GetAllEmpDetails");
            }
            catch
            {
                return View();
            }
        }
        [Area("Admin")]
        // GET: Employee/DeleteEmp/5    
        public ActionResult DeleteEmp(int id)
        {
            try
            {
                BranchViewModel EmpRepo = new BranchViewModel();
                if (EmpRepo.DeleteEmployee(id))
                {
                    ViewBag.AlertMsg = "Branch details deleted successfully";

                }
                return RedirectToAction("GetAllEmpDetails");

            }
            catch
            {
                return View();
            }
        }

    }
}

Areas/Admin/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InventoryApplication.Areas.Admin.Models;
using InventoryApplication.Areas.Admin.ViewModel;
using Microsoft.AspNetCore.Mvc;


namespace InventoryApplication.Areas.Admin.Controllers
{
    public class CountryController : Controller
    {
        BranchAccessLayer objCustomer = new BranchAccessLayer();
        [Area("Admin")]

        public ActionResult GetAllCountryDetails()
        {

            CountryViewModel EmpRepo = new CountryViewModel();
            ModelState.Clear();
            return View(EmpRepo.GetAllCountry());
        }
        // GET: Employee/AddEmployee   
        [Area("Admin")]
        public ActionResult AddCountry()
        {
            return View();
        }
        [Area("Admin")]
        // POST: Employee/AddEmployee    
        [HttpPost]
        public ActionResult AddCountry(CountryModel Emp)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    CountryViewModel EmpRepo = new CountryViewModel();

                    if (EmpRepo.AddCountry(Emp))
                    {
                        ViewBag.Message = "Country details added successfully";
                    }
                }

                return View();
            }
            catch
            {
                return View();
            }
        }
        [Area("Admin")]
        // GET: Employee/EditEmpDetails/5    
        public ActionResult EditCountryDetails(int id)
        {
            CountryViewModel EmpRepo = new CountryViewModel();



            return View(EmpRepo.GetAllCountry().Find(Emp => Emp.Id == id));

        }

        // POST: Employee/EditEmpDetails/5    
        [HttpPost]
        [Area("Admin")]
        public ActionResult EditCountryDetails(int id, CountryModel obj)
        {
            try
            {
                CountryViewModel EmpRepo = new CountryViewModel();

                EmpRepo.UpdateCountry(obj);
                return RedirectToAction("GetAllCountryDetails");
            }
            catch
            {
                return View();
            }
        }
        [Area("Admin")]
        // GET: Employee/DeleteEmp/5    
        public ActionResult DeleteCountry(int id)
        {
            try
            {
                CountryViewModel EmpRepo = new CountryViewModel();
                if (EmpRepo.DeleteCountry(id))
                {
                    ViewBag.AlertMsg = "Country details deleted successfully";

                }
                return RedirectToAction("GetAllCountryDetails");

            }
            catch
            {
                return View();
            }
        }

    }
}

Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <title>24 Carat Pure and Simple</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="~/assets/vendor/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/assets/vendor/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/assets/vendor/linearicons/style.css" />
    <link rel="stylesheet" href="~/assets/vendor/chartist/css/chartist-custom.css" />
    <!-- MAIN CSS -->


    <link rel="stylesheet" href="~/assets/css/main.css" />
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="~/Areas/Admin/assets/css/demo.css" />
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet" />

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <!-- ICONS -->

    <link rel="apple-touch-icon" sizes="76x76" href="~/Areas/Admin/assets/img/apple-icon.png" />

    <style>
        table {
            border: 1px solid #ddd !important;
        }

        .txt {
            width: 100%;
            padding: 8px 10px;
            border: 1px solid #ccc;
            box-sizing: border-box;
            border-radius: 0px;
            outline: none;
            margin-bottom: 15px;
            box-shadow: 1px 1px 7px 0px #4f5454;
        }

        .txt1 {
            width: 100%;
            padding: 8px 10px;
            border: 1px solid #ccc;
            box-sizing: border-box;
            border-radius: 0px;
            outline: none;
            box-shadow: 1px 1px 7px 0px #4f5454;
        }

        .btn {
            background-color: #fa5524;
            box-sizing: border-box;
            border: 1px solid #fe4f72;
            outline: none;
            /*border-radius:;
            padding: 10px 24px;*/
            font-size: 0.9em;
            color: white;
            font-family: verdana;
            /*box-shadow : 1px 1px 7px 0px #4f5454;*/
        }

        input[type=text]:focus {
            background-color:;
        }

        .mrgbtm_fntfmly {
            margin: 0px 0px 4px 0px;
            font-family: Arial;
        }
    </style>
    <style type="text/css">
        td, th {
            padding: 2px;
        }

        .GridPager a, .GridPager span {
            display: block;
            /*height: 15px;*/
            width: 20px;
            font-weight: bold;
            text-align: center;
            text-decoration: none;
        }

        .GridPager a {
            background-color: #f5f5f5;
            color: #969696;
            border: 1px solid #969696;
        }

        .GridPager span {
            background-color: #A1DCF2;
            color: #000;
            border: 1px solid #3AC0F2;
        }
    </style>
</head>
<body>
    <div id="wrapper">
        <!-- NAVBAR -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="brand" style="padding:5px 69px;">

                <a href="#"><h3>RICE MILL</h3></a>
            </div>
            <div class="container-fluid">
                <div class="navbar-btn" style="padding:14px;margin-bottom:1px">
                    <button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
                </div>

              		<div class="navbar-btn navbar-btn-right">
                    <a class="btn btn-success update-pro" href="#" title="Upgrade to Pro" target="_blank"><i class="fa fa-rocket"></i> <span></span></a>
                </div>
                <div id="navbar-menu">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                                <i class="lnr lnr-alarm"></i>
                                <span class="badge bg-danger">5</span>
                            </a>
                            <ul class="dropdown-menu notifications">
                                <li><a href="#" class="notification-item"><span class="dot bg-warning"></span>System space is almost full</a></li>
                                <li><a href="#" class="notification-item"><span class="dot bg-danger"></span>You have 9 unfinished tasks</a></li>
                                <li><a href="#" class="notification-item"><span class="dot bg-success"></span>Monthly report is available</a></li>
                                <li><a href="#" class="notification-item"><span class="dot bg-warning"></span>Weekly meeting in 1 hour</a></li>
                                <li><a href="#" class="notification-item"><span class="dot bg-success"></span>Your request has been approved</a></li>
                                <li><a href="#" class="more">See all notifications</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="lnr lnr-question-circle"></i> <span>Help</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Basic Use</a></li>
                                <li><a href="#">Working With Data</a></li>
                                <li><a href="#">Security</a></li>
                                <li><a href="#">Troubleshooting</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span>Admin</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="#"><i class="lnr lnr-user"></i> <span>My Profile</span></a></li>
                                <li><a href="#"><i class="lnr lnr-envelope"></i> <span>Message</span></a></li>
                                <li><a href="#"><i class="lnr lnr-cog"></i> <span>Settings</span></a></li>
                                <li><a href="#"><i class="lnr lnr-exit"></i> <span>Logout</span></a></li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
        <!-- END NAVBAR -->
        <!-- LEFT SIDEBAR -->
        <div id="sidebar-nav" class="sidebar">
            <div class="sidebar-scroll">
                <nav>
                    <ul class="nav">
                        <li></li>
                        <li>
                            <a href="#10" data-toggle="collapse" class="collapsed"><i class="lnr lnr-file-empty"></i>  <span> Update</span><i class="icon-submenu lnr lnr-chevron-left"></i></a>
                            <div id="10" class="collapse ">
                                <ul class="nav">
                                    <li> @Html.ActionLink("Home Page", "DashBoard", "AdminDashBoard")</li>
                                    @*<li> <a href="@Url.Action("Index", "BranchMaster", new { @Area = "Admin" })">Branch Master</a></li>*@
                                    <li> @Html.ActionLink("Branch Entery", "GetAllEmpDetails", "Branch")</li>
                                    <li> @Html.ActionLink("Country Entery", "GetAllCountryDetails", "Country")</li>

                                </ul>
                            </div>
                        </li>
                        <li>
                            <a href="#1" data-toggle="collapse" class="collapsed"><i class="lnr lnr-file-empty"></i> <span>Product</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
                            <div id="1" class="collapse ">
                                <ul class="nav">
                                    <li><a href="frmproduct.aspx" class="">Add Product</a></li>
                                    <li><a href="ProductDetail.aspx" class=""> Product Detail</a></li>
                                </ul>
                            </div>
                        </li>
                        <li><a href="OrderStatus.aspx" class=""><i class="lnr lnr-file-empty"></i>  <span>Payment Approval</span></a></li>
                        <li><a href="Report_Order.aspx" class=""><i class="lnr lnr-file-empty"></i>  <span>Order</span></a></li>
                        <li><a href="AddNotice.aspx" class=""><i class="lnr lnr-file-empty"></i>  <span>Notice</span></a></li>


                        <li><a href="logout.aspx" class=""><i class="lnr lnr-exit"></i> <span>Logout</span></a></li>

                    </ul>
                </nav>
            </div>
        </div>
        <div>
            @RenderBody()
        </div>
        <script src="~/assets/vendor/jquery/jquery.min.js"></script>
        <script src="~/assets/vendor/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js"></script>
        @*<script src="~/Areas/Admin/assets/vendor/jquery/jquery.js"></script>*@
        <script src="~/assets/scripts/klorofil-common.js"></script>
        <script>
          function checkDec(el) {
              var ex = /^[0-9]+\.?[0-9]*$/;
              if (ex.test(el.value) == false) {
                  el.value = el.value.substring(0, el.value.length - 1);
              }
          }
        </script>
</body>
</html>