Areas/Admin/Controllers/StateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using System.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using System.IO;
using InventoryApplication.Areas.Admin.ViewModel;
using InventoryApplication.Areas.Admin.Models;

namespace InventoryApplication.Areas.Admin.Controllers
{
    public class StateController : Controller
    {

        [Area("Admin")]

        public ActionResult Index()
        {
            StateModel sd = new StateModel();
               StateViewModel fruit = new StateViewModel();
               sd .Countrys = fruit.PopulateFruits();
            return View();
        }

        [Area("Admin")]
        [HttpPost]
        public ActionResult Index(StateModel State)
        {
            StateViewModel fruit = new StateViewModel();
            State.Countrys = fruit. PopulateFruits();
            var selectedItem = State.Countrys.Find(p => p.Value == State.Countryid.ToString());
            if (selectedItem != null)
            {
                selectedItem.Selected = true;
               
            }

            return View(fruit);
        }


    }
}

Areas/Admin/Views/State/Index.cshtml
@model InventoryApplication.Areas.Admin.Models.StateModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }
    </style>
</head>
<body>
    @using (Html.BeginForm("Index", "State", FormMethod.Post))
    {
        <table>
            <tr>
                <td>
                    Fruit:
                </td>
                <td>
                    @Html.DropDownListFor(m => m.Countryid, Model.Countrys, "Please select")
                </td>
            </tr>
            <tr>
                <td>
                    Quantity:
                </td>
                <td>
                    @Html.TextBoxFor(m => m.StateName)
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Submit" />
                </td>
            </tr>
        </table>
    }
    @if (ViewBag.Message != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
            };
        </script>
    }
</body>
</html>